-- MySQL 5.7+ / 8+ : Plan con 100.000 materias (sin CTE y sin reusar temp table)
START TRANSACTION;

SET @plan_id  := 8;
SET @base_id  := 11158;     -- primera materia de este plan
SET @cantidad := 100000;    -- 100.000

-- 1) Crear el plan
INSERT INTO PlanEstudio (idPlan, nomPlan)
VALUES (@plan_id, 'Plan Ultra (100000 materias)');

-- 2) Tabla temporal con números 0..99999 (100.000 filas)
CREATE TEMPORARY TABLE tmp_nums (
  n INT NOT NULL PRIMARY KEY
);

INSERT INTO tmp_nums (n)
SELECT
  d0.d
  + d1.d * 10
  + d2.d * 100
  + d3.d * 1000
  + d4.d * 10000 AS n
FROM
  (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
   UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d0
CROSS JOIN
  (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
   UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d1
CROSS JOIN
  (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
   UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d2
CROSS JOIN
  (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
   UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d3
CROSS JOIN
  (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
   UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d4;

-- 3) Insertar 100.000 materias
INSERT INTO Materia (idMateria, nomMateria, numCreditos)
SELECT
  @base_id + n AS idMateria,
  CONCAT('Materia ', @base_id + n, ' (Plan Ultra)') AS nomMateria,
  ((@base_id + n) % 4) + 1 AS numCreditos
FROM tmp_nums
WHERE n < @cantidad;

-- 4) Asignarlas al plan
INSERT INTO MateriaPorPlan (idPlan, idMateria)
SELECT
  @plan_id,
  @base_id + n
FROM tmp_nums
WHERE n < @cantidad;

DROP TEMPORARY TABLE tmp_nums;

COMMIT;
